version: "3.2"
services:
  php:
    build: 
      context: './php/'
      args:
       PHP_VERSION: ${PHP_VERSION}
    networks:
      - backend
    volumes:
      - ../:/var/www/html/
    container_name: csphp
    restart: always
networks:
  backend:
